# permissions for end users to edit teamspeakservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teamspeakserver-editor-role
rules:
- apiGroups:
  - voip.replicas.io
  resources:
  - teamspeakservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - voip.replicas.io
  resources:
  - teamspeakservers/status
  verbs:
  - get
