// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomaticRollout) DeepCopyInto(out *AutomaticRollout) {
	*out = *in
	in.WindowStart.DeepCopyInto(&out.WindowStart)
	in.WindowStop.DeepCopyInto(&out.WindowStop)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomaticRollout.
func (in *AutomaticRollout) DeepCopy() *AutomaticRollout {
	if in == nil {
		return nil
	}
	out := new(AutomaticRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	in.ConfigManaged.DeepCopyInto(&out.ConfigManaged)
	out.ConfigUnmanaged = in.ConfigUnmanaged
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Database.
func (in *Database) DeepCopy() *Database {
	if in == nil {
		return nil
	}
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfigManaged) DeepCopyInto(out *DatabaseConfigManaged) {
	*out = *in
	in.Persistence.DeepCopyInto(&out.Persistence)
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfigManaged.
func (in *DatabaseConfigManaged) DeepCopy() *DatabaseConfigManaged {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfigManaged)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfigUnmanaged) DeepCopyInto(out *DatabaseConfigUnmanaged) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfigUnmanaged.
func (in *DatabaseConfigUnmanaged) DeepCopy() *DatabaseConfigUnmanaged {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfigUnmanaged)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseStatus) DeepCopyInto(out *DatabaseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseStatus.
func (in *DatabaseStatus) DeepCopy() *DatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Persistence) DeepCopyInto(out *Persistence) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Persistence.
func (in *Persistence) DeepCopy() *Persistence {
	if in == nil {
		return nil
	}
	out := new(Persistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	in.LastRollout.DeepCopyInto(&out.LastRollout)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpeak) DeepCopyInto(out *TeamSpeak) {
	*out = *in
	in.Persistence.DeepCopyInto(&out.Persistence)
	in.AutomaticRollout.DeepCopyInto(&out.AutomaticRollout)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpeak.
func (in *TeamSpeak) DeepCopy() *TeamSpeak {
	if in == nil {
		return nil
	}
	out := new(TeamSpeak)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpeakServer) DeepCopyInto(out *TeamSpeakServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpeakServer.
func (in *TeamSpeakServer) DeepCopy() *TeamSpeakServer {
	if in == nil {
		return nil
	}
	out := new(TeamSpeakServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamSpeakServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpeakServerList) DeepCopyInto(out *TeamSpeakServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TeamSpeakServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpeakServerList.
func (in *TeamSpeakServerList) DeepCopy() *TeamSpeakServerList {
	if in == nil {
		return nil
	}
	out := new(TeamSpeakServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamSpeakServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpeakServerSpec) DeepCopyInto(out *TeamSpeakServerSpec) {
	*out = *in
	in.TeamSpeak.DeepCopyInto(&out.TeamSpeak)
	in.Database.DeepCopyInto(&out.Database)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpeakServerSpec.
func (in *TeamSpeakServerSpec) DeepCopy() *TeamSpeakServerSpec {
	if in == nil {
		return nil
	}
	out := new(TeamSpeakServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpeakServerStatus) DeepCopyInto(out *TeamSpeakServerStatus) {
	*out = *in
	in.TeamSpeak.DeepCopyInto(&out.TeamSpeak)
	out.Database = in.Database
	in.LastUpdate.DeepCopyInto(&out.LastUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpeakServerStatus.
func (in *TeamSpeakServerStatus) DeepCopy() *TeamSpeakServerStatus {
	if in == nil {
		return nil
	}
	out := new(TeamSpeakServerStatus)
	in.DeepCopyInto(out)
	return out
}
